### ISSUE TITLE
Archive this package

### ISSUE THREAD

**Issue by jsiedentop** [dartclub/linter_rules#3]
We have [decided](https://github.com/dartclub/turf_dart/issues/156) to stop using dartclub_lint and use the standard linter instead. 

My suggestion would be: 
- [x] Document it in Readme.md
- [x] Archive this repo
- [x] Delete all references
- [x] Unlist it on pub.dev

@lukas-h any complaints?

**Comment by lukas-h** [comment]
sounds good.

@grundid do you still use this package somewhere?

**Comment by grundid** [comment]
No, i dont
